### ISSUE TITLE
Add option to support retrying pushing to docker hub

### ISSUE THREAD

**Issue by mhahn** [harbur/captain#34] opened 2016-01-30 23:42 UTC
I've run into a lot of sporadic errors pushing to docker hub, retrying always fixes it. it would be great to have an option to retry pushing images up to 3 times.

**Comment by spiddy** [comment] 2016-05-18 16:21
Docker CLI doesn't try to resolve server errors with retry options and neither should captain's scope IMO. The problem is related to missing error handling from captain (issue #39 which is resolved for next release). Now you should be able to script-iterate on top of captain for such cases by checking the exit code.

Would that solve the issue for conveyor?

**Comment by spiddy** [comment] 2016-05-24 07:37
closing, if you still consider it's needed please re-open it and we can discuss it further.

**Closed by spiddy** 2016-05-24 07:37 UTC
Labels: enhancement, wontfix
